ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'MOVING_CARRYING';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'GARDEN_WORK';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'DELIVERY_TRANSPORT';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'SMALL_REPAIRS';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'PET_CARE';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'TECHNICAL_HELP';
