"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLanguage = "no" | "en";

type I18n = {
  lang: AppLanguage;
  setLang: (lang: AppLanguage) => void;
  t: (key: string) => string;
};

const messages: Record<AppLanguage, Record<string, string>> = {
  no: {
    appName: "ServNest",
    menu: "Meny",
    dashboard: "Dashboard",
    prices: "Priser",
    myOrdersMenu: "Mine oppdrag",
    myOrdersHint: "Alle oppdrag som gjelder deg vises her. Filtrer mellom pågående, fullført og alle.",
    myOrdersStatusFilter: "Statusfilter",
    myOrdersFilterOngoing: "Pågående",
    myOrdersFilterCompleted: "Fullført",
    myOrdersFilterAll: "Alle",
    home: "Hjem",
    newOrder: "Ny bestilling",
    profile: "Profil",
    profileTitle: "Min profil",
    settings: "Innstillinger",
    language: "Språk",
    activeMode: "Aktiv visning",
    role: "Rolle",
    access: "Tilgang",
    switchView: "Bytt visning",
    users: "Brukere",
    deleteUsersMenu: "Slett brukere",
    logout: "Logg ut",
    viewAsAdmin: "Vis som admin",
    viewAsLandlord: "Vis som utleier",
    viewAsWorker: "Vis som tjenesteutfører",
    login: "Logg inn",
    loginSubtitle: "Internt system for Airbnb drift",
    invalidCredentials: "Ugyldig e-post eller passord",
    loginUnknownError: "Innlogging feilet. Prøv igjen.",
    loginSessionError: "Innlogging ble godkjent, men vi klarte ikke å opprette en aktiv sesjon. Prøv igjen.",
    forgotPassword: "Glemt passord?",
    resetPassword: "Tilbakestill passord",
    resetPasswordSubtitle: "Skriv e-post og nytt passord for å sette passordet på nytt.",
    newPassword: "Nytt passord",
    resetPasswordSuccess: "Passord er oppdatert. Du kan nå logge inn.",
    resetPasswordFailed: "Kunne ikke oppdatere passord",
    backToLogin: "Tilbake til innlogging",
    email: "E-post",
    phone: "Telefon",
    password: "Passord",
    showPassword: "Vis passord",
    hidePassword: "Skjul passord",
    noAccount: "Ingen konto?",
    register: "Registrer",
    registerAccount: "Registrer konto",
    name: "Navn",
    passwordMin: "Passord (min. 8)",
    roleLandlordOnly: "Kun utleier",
    roleWorkerOnly: "Kun tjenesteutfører",
    roleBoth: "Både utleier og tjenesteutfører",
    alreadyAccount: "Har konto?",
    cannotRegister: "Kunne ikke registrere bruker",
    registerReasonEmailExists: "E-postadressen er allerede registrert.",
    registerReasonInvalidPayload: "Ugyldig registreringsdata. Sjekk feltene og prøv igjen.",
    registerReasonDbUnavailable: "Registrering er midlertidig utilgjengelig fordi databasen ikke er tilgjengelig.",
    registerReasonUnknown: "Registrering feilet på serversiden. Prøv igjen senere.",
    registerAutoLoginFailed: "Bruker ble opprettet, men automatisk innlogging feilet. Logg inn manuelt.",
    overview: "Oversikt over oppdrag og aktivitet",
    jobs: "Oppdrag",
    type: "Type",
    address: "Adresse",
    date: "Dato",
    status: "Status",
    details: "Detaljer",
    action: "Handling",
    loadingJobs: "Laster oppdrag...",
    noJobs: "Ingen oppdrag ennå.",
    open: "Åpne",
    takeJob: "Ta oppdrag",
    assigned: "Tildelt",
    cannotTakeJob: "Kunne ikke ta oppdrag",
    takenJob: "Oppdrag påtatt",
    activeJobs: "Aktive oppdrag",
    completedJobs: "Fullførte",
    landlords: "Utleiere",
    workers: "Tjenesteutførere",
    messages: "Meldinger",
    messageCenter: "Meldingsoversikt",
    noMessagesYet: "Ingen meldinger ennå.",
    openConversation: "Åpne samtale",
    conversationWith: "Samtale med",
    unassignedWorker: "Ikke tildelt ennå",
    openMap: "Kart",
    contact: "Kontakt",
    contactLandlord: "Kontakt utleier",
    contactWorker: "Kontakt tjenesteutfører",
    reviews: "Vurderinger",
    averageRating: "Snittscore",
    feedbackFromOthers: "Tilbakemeldinger fra andre",
    noReviewsYet: "Ingen tilbakemeldinger ennå.",
    sendMessage: "Send melding",
    writeMessage: "Skriv melding",
    sending: "Sender...",
    send: "Send",
    cannotSendMessage: "Kunne ikke sende melding",
    messageSent: "Melding sendt",
    roleAdmin: "Admin",
    roleLandlord: "Utleier",
    roleWorker: "Tjeneste",
    newMessages: "Nye meldinger",
    markAsRead: "Marker som lest",
    switchModeFailed: "Kunne ikke bytte visning. Kontroller at brukeren har begge roller.",
    switchModeUpdated: "Visning oppdatert",
    profileSwitchFailed: "Kunne ikke bytte modus. Kontroller at brukeren har begge roller.",
    profileModeUpdated: "Modus oppdatert",
    profileEditSection: "Endre profilinformasjon",
    saveProfile: "Lagre profil",
    profileUpdated: "Profil oppdatert",
    profileUpdateFailed: "Kunne ikke oppdatere profil",
    dangerZone: "Faresone",
    deleteMyAccount: "Slett min konto",
    deleteAccountHint: "Dette deaktiverer kontoen din og logger deg ut.",
    confirmDeleteMyAccount: "Er du sikker på at du vil slette kontoen din?",
    deleteAccountSuccess: "Konto slettet",
    deleteAccountFailed: "Kunne ikke slette konto",
    settingsHint: "Bruk menyen øverst til høyre for språk, visningsmodus og kontohandlinger.",
    mobileNotifications: "Mobilvarsler",
    pushStatusTitle: "Push-status",
    pushActiveDevices: "Aktive enheter",
    pushPreference: "Varslingsinnstilling",
    pushLatestSync: "Siste token-sync",
    sendTestPush: "Send testvarsel",
    pushTestSent: "Testvarsel sendt",
    pushTestFailed: "Kunne ikke sende testvarsel",
    pushDisabled: "Mobilvarsler er slått av for brukeren",
    pushNoActiveTokens: "Ingen aktive mobilenheter registrert ennå",
    noDataYet: "Ingen data ennå",
    saveSettings: "Lagre innstillinger",
    settingsSaved: "Innstillinger lagret",
    settingsSaveFailed: "Kunne ikke lagre innstillinger",
    userCreated: "Bruker opprettet",
    userUpdated: "Bruker oppdatert",
    deleteUser: "Slett bruker",
    confirmDeleteUser: "Er du sikker på at du vil slette brukeren",
    userDeleted: "Bruker slettet",
    deleteUserFailed: "Kunne ikke slette bruker",
    genericError: "Noe gikk galt. Prøv igjen.",
    unauthorizedError: "Du må logge inn for å fortsette.",
    forbiddenError: "Du har ikke tilgang til denne handlingen.",
    notFoundError: "Fant ikke det du leter etter.",
    conflictError: "Handling kunne ikke fullføres på grunn av konflikt i data.",
    serviceUnavailableError: "Tjenesten er midlertidig utilgjengelig. Prøv igjen snart.",
    workerChecklist: "Sjekkliste før fullføring",
    completionNote: "Beskjed til utleier",
    completeWithNote: "Fullfør med beskjed",
    completeOrderFailed: "Kunne ikke fullføre oppdrag",
    completionDetails: "Utførelsesrapport",
    noCompletionDetails: "Ingen utførelsesrapport ennå.",
    reviewWorker: "Gi tilbakemelding",
    rating: "Vurdering (1-5)",
    reviewComment: "Tilbakemeldingstekst",
    reviewPrompt: "Velg stjerner og skriv en kort tilbakemelding om tjenesteutføreren.",
    reviewStarLabel: "Stjerner",
    reviewTextPlaceholder: "Skriv hva som fungerte bra og hva som kan bli bedre",
    reviewSubmitted: "Tilbakemelding sendt",
    reviewFailed: "Kunne ikke sende tilbakemelding",
    guestCount: "Antall gjester",
    guestCountHint: "Antall gjester boligen skal klargjøres for (utvask).",
    bedReady: "Senger er gjort klare",
    bathroomClean: "Bad er rengjort",
    kitchenClean: "Kjøkken er rengjort",
    floorsVacuumed: "Gulv er støvsugd/vasket",
    trashHandled: "Søppel er håndtert",
    keysHandled: "Nøkler er håndtert",
    towelsPrepared: "Er håndklær klargjort",
    suppliesRefilled: "Er det fylt på med toalettpapir, tørkepapir og håndsåpe",
    allRoomsPhotographed: "Er det tatt bilder av alle rom",
    userNotFound: "Bruker ikke funnet.",
    loading: "Laster...",
    filter: "Filter",
    landlordName: "Utleiernavn",
    workerName: "Tjenesteutfører",
    postedDate: "Dato utlyst",
    completedDate: "Dato utført",
    serviceType: "Tjenestetype",
    serviceState: "Tjenestestatus",
    all: "Alle",
    openUnassigned: "Utlyst, ikke tildelt",
    orderIdNumber: "ID-nummer",
    responsible: "Ansvarlig",
    completedService: "Utført",
    ongoingService: "Pågår",
    announcedService: "Utlyst",
    statusPending: "Venter",
    statusInProgress: "Pågår",
    statusCompleted: "Fullført",
    prev: "Forrige",
    next: "Neste",
    sortNewestOldest: "Nyest til eldst",
    sortOldestNewest: "Eldst til nyest",
    sortNearest: "Nærmest",
    searchJobs: "Søk i oppdrag...",
    completedOrdersMenu: "Fullførte oppdrag",
    completedOrdersHint: "Alle fullførte oppdrag vises her.",
    createUserTitle: "Opprett bruker",
    allUsersTitle: "Alle brukere",
    userStatus: "Brukerstatus",
    userActive: "Aktiv",
    userInactive: "Deaktivert",
    activate: "Aktiver",
    deactivate: "Deaktiver",
    create: "Opprett",
    serviceLabel: "Tjeneste",
    dateLabel: "Dato",
    selectTime: "Velg tidspunkt",
    timeSlotHalfHourOnly: "Velg et klokkeslett på hel eller halv time",
    addressLabel: "Adresse",
    commentLabel: "Kommentar",
    saving: "Lagrer...",
    createOrderAction: "Opprett bestilling",
    createOrderSuccess: "Bestilling opprettet",
    selectLandlord: "Velg utleier",
    searchLandlord: "Skriv for å søke etter utleier",
    invalidLandlordSelection: "Velg en gyldig utleier fra listen",
    statusUpdated: "Status oppdatert",
    orderAssignedSuccess: "Oppdrag tildelt",
    imageUploadedSingle: "Bilde lastet opp",
    imageUploadedMultiple: "bilder lastet opp",
    messageDeleted: "Melding slettet",
    orderUpdated: "Oppdrag oppdatert",
    orderDeleted: "Oppdrag slettet",
    orderTitle: "Oppdrag",
    landlordLabel: "Utleier",
    assignedLabel: "Tildelt",
    noneAssigned: "Ingen",
    manageOrder: "Administrer oppdrag",
    cancel: "Avbryt",
    edit: "Rediger",
    addressDateRequired: "Adresse og dato er påkrevd",
    invalidServiceType: "Ugyldig tjenestetype",
    guestCountRange: "Antall gjester må være mellom 1 og 50",
    confirmDeleteMessage: "Vil du slette denne meldingen?",
    confirmDeleteOrder: "Er du sikker på at du vil slette dette oppdraget?",
    deleteLabel: "Slett",
    selectWorker: "Velg tjenesteutfører",
    assigning: "Tildeler...",
    assignAction: "Tildel",
    uploadImage: "Bilde",
    uploadType: "Type",
    beforeLabel: "Før",
    afterLabel: "Etter",
    uploadAction: "Last opp",
    privateChat: "Privat chat",
    privateChatHint: "Kun mellom utleier og tjenesteutfører",
    chatPendingHint: "Chat aktiveres automatisk når oppdraget er tatt av en tjenesteutfører.",
    orderStartRequired: "Du må trykke START før du kan skrive eller gjøre endringer i dette oppdraget.",
    orderStartRequiredHint: "Trykk START for å låse opp chat, bildeopplasting, kommentarer og utførelsesrapport.",
    workerSequenceBlocked: "Du må fullføre tidligere oppdrag før du kan starte dette.",
    writeComment: "Skriv kommentar",
    noImagesYet: "Ingen bilder lastet opp ennå.",
    writeMessagePlaceholder: "Skriv melding",
    newMessageNotice: "Du har en ny melding",
    mapPreviewTitle: "Kartforhåndsvisning",
    miniMap: "Mini kart",
    guestCountPlaceholder: "Antall gjester (valgfritt)",
    notePlaceholder: "Notat",
    saveChanges: "Lagre endringer",
    deleteOrderAction: "Slett oppdrag",
    deleteOrderBusy: "Sletter...",
    sendReceipt: "Send kvittering",
    sendReceiptBusy: "Sender...",
    receiptLabel: "Kvittering",
    checklistMissing: "Mangler",
    startAction: "Start",
    receiptAmountPrompt: "Beløp i NOK for kvittering",
    invalidAmount: "Ugyldig beløp",
    receiptSent: "Kvittering sendt",
    paymentSectionTitle: "Betaling",
    paymentStatusNotStarted: "Ikke startet",
    paymentStatusPending: "Venter på betaling",
    paymentStatusPaid: "Betalt",
    paymentAmountLabel: "Beløp",
    paymentPaidAtLabel: "Betalt",
    paymentCreateAction: "Opprett betaling",
    paymentConfirmAction: "Bekreft betaling",
    paymentResendReceipt: "Send kvittering på nytt",
    paymentAmountPrompt: "Beløp i NOK for betaling",
    paymentCreated: "Betaling opprettet",
    paymentConfirmed: "Betaling bekreftet",
    orderImagesTitle: "Bilder av din leilighet",
    workerImageCountLabel: "Antall bilder fra tjenesteutfører",
    showMoreImages: "Vis flere bilder",
    privacyLabel: "Personvern",
    termsLabel: "Vilkår",
    supportLabel: "Support",
    tapOpenJob: "Trykk for å åpne oppdrag",
    noAccessTitle: "Ingen tilgang",
    adminAccessRequired: "Denne siden krever admin-tilgang.",
    fullUserOverviewTitle: "Full brukeroversikt",
    fullUserOverviewSubtitle: "Alle brukere i appen med roller, tilganger, status og aktivitet.",
    totalLabel: "Totalt",
    activePluralLabel: "Aktive",
    adminsLabel: "Admin",
    landlordsLabel: "Utleiere",
    workersLabel: "Tjenesteutførere",
    permissionsLabel: "Tilganger",
    activeModeLabel: "Aktiv modus",
    createdLabel: "Opprettet",
    landlordOrdersLabel: "Ordre (utleier)",
    assignedOrdersLabel: "Ordre (ansvarlig)",
    pushLabel: "Push",
    landlordAndWorkerAccess: "Utleier + Tjeneste",
    notFoundUserPanel: "Bruker ikke funnet.",
    accountRoleLabel: "Konto-rolle",
    activeRoleLabel: "Aktiv rolle",
    systemHealth: "Systemstatus",
    refresh: "Oppdater",
    appApi: "App/API",
    database: "Database",
    statusOk: "OK",
    statusError: "Feil",
    lastChecked: "Sist sjekket",
    priceCalcTitle: "Velg tjenester og se sluttsum",
    priceCalcSubtitle: "Dette er totalsummen kunden må betale for at tjenesten skal leveres.",
    priceCalcCleaning: "Rengjøring",
    priceCalcKeyDelivery: "Nøkkellevering",
    priceCalcHomeSize: "Boligstørrelse (m²)",
    priceCalcLaundryWeight: "Vekt på vask (kg)",
    priceCalcBreakfast: "Frokostbrett (per person)",
    priceCalcClothesLaundry: "Klesvask (per plagg)",
    priceCalcTotal: "Sluttsum som må betales",
    priceCalcNotSelected: "Ikke valgt",
    priceCalcAreaSurcharge: "Tillegg for størrelse",
    priceCalcPaymentInfo: "Bestillingen bekreftes når dette beløpet er betalt.",
    priceCalcDetails: "Prisdetaljer",
    priceCalcActiveKgPrice: "Aktiv kg-pris",
    pricePackageTitle: "Pakkepris",
    pricePackageCleaningTitle: "Grundig rengjøring",
    pricePackageKeyDeliveryTitle: "Nøkkellevering",
    pricePackageLaundryTitle: "Vask av sengetøy og håndklær",
    pricePackageCleaningWeekday: "Pakke: Hverdag (500 kr)",
    pricePackageCleaningWeekend: "Pakke: Helg (600 kr)",
    pricePackageKeyBefore18: "Pakke: Hverdag før kl. 18:00 (400 kr)",
    pricePackageKeyAfter18Weekend: "Pakke: Etter kl. 18:00 / helg (500 kr)",
    pricePackageCleaningWeekdayLabel: "Pakkepris rengjøring - hverdag",
    pricePackageCleaningWeekendLabel: "Pakkepris rengjøring - helg",
    pricePackageKeyBefore18Label: "Pakkepris nøkkellevering - hverdag før kl. 18:00",
    pricePackageKeyAfter18WeekendLabel: "Pakkepris nøkkellevering - etter kl. 18:00 og i helger",
    pricePackageLaundryLine: "Henting, vask, tørk, bretting og levering: 60 kr per kg",
    priceApartmentLimit: "Gjelder leiligheter opptil 75 m².",
    priceAreaAddition: "For hver påbegynte 25 m² over dette legges det til 100 kr.",
    priceSuppliesInfo: "Eventuelle forbruksvarer som håndsåpe og toalettpapir dekkes av utleier.",
    priceSingleTitle: "Enkeltpriser",
    priceSingleCleaningTitle: "Rengjøring",
    priceSingleKeyDeliveryTitle: "Nøkkellevering",
    priceSingleLaundryTitle: "Vask av sengetøy og håndklær",
    priceSingleCleaningWeekday: "Enkelt: Hverdag (600 kr)",
    priceSingleCleaningWeekend: "Enkelt: Helg (700 kr)",
    priceSingleKeyWeekday: "Enkelt: Hverdag (500 kr)",
    priceSingleKeyWeekend: "Enkelt: Helg (700 kr)",
    priceSingleCleaningWeekdayLabel: "Enkeltpris rengjøring - hverdag",
    priceSingleCleaningWeekendLabel: "Enkeltpris rengjøring - helg",
    priceSingleKeyWeekdayLabel: "Enkeltpris nøkkellevering - hverdag",
    priceSingleKeyWeekendLabel: "Enkeltpris nøkkellevering - helg",
    priceSingleCleaningAddition: "Tillegg: 100 kr per påbegynte 25 m² over 75 m².",
    priceSingleLaundryLine: "Henting, vask, tørk og levering: 65 kr per kg",
    priceGuestOffersTitle: "Tilbud for gjester",
    priceBreakfastTitle: "Frokostbrett",
    priceBreakfastLine: "350 kr per person",
    priceClothesLaundryTitle: "Klesvask",
    priceClothesLaundryLine: "Henting, vasking, tørking, bretting og levering: 45 kr per plagg",
    priceClothesLaundryNote: "Gjelder ikke tunge eller store plagg som for eksempel jakker.",
    importantField: "Viktig felt",
    serviceCleaningName: "Utvask",
    serviceKeyHandlingName: "Nøkkelhåndtering",
  },
  en: {
    appName: "ServNest",
    menu: "Menu",
    dashboard: "Dashboard",
    prices: "Prices",
    myOrdersMenu: "My jobs",
    myOrdersHint: "All jobs relevant to you are shown here. Filter between ongoing, completed, and all.",
    myOrdersStatusFilter: "Status filter",
    myOrdersFilterOngoing: "Ongoing",
    myOrdersFilterCompleted: "Completed",
    myOrdersFilterAll: "All",
    home: "Home",
    newOrder: "New order",
    profile: "Profile",
    profileTitle: "My profile",
    settings: "Settings",
    language: "Language",
    activeMode: "Active mode",
    role: "Role",
    access: "Access",
    switchView: "Switch view",
    users: "Users",
    deleteUsersMenu: "Delete users",
    logout: "Sign out",
    viewAsAdmin: "View as admin",
    viewAsLandlord: "View as landlord",
    viewAsWorker: "View as service worker",
    login: "Sign in",
    loginSubtitle: "Internal system for Airbnb operations",
    invalidCredentials: "Invalid email or password",
    loginUnknownError: "Sign-in failed. Please try again.",
    loginSessionError: "Sign-in was accepted, but we could not establish an active session. Please try again.",
    forgotPassword: "Forgot password?",
    resetPassword: "Reset password",
    resetPasswordSubtitle: "Enter your email and a new password to reset it.",
    newPassword: "New password",
    resetPasswordSuccess: "Password updated. You can sign in now.",
    resetPasswordFailed: "Could not update password",
    backToLogin: "Back to sign in",
    email: "Email",
    phone: "Phone",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    noAccount: "No account?",
    register: "Register",
    registerAccount: "Create account",
    name: "Name",
    passwordMin: "Password (min. 8)",
    roleLandlordOnly: "Landlord only",
    roleWorkerOnly: "Service worker only",
    roleBoth: "Both landlord and service worker",
    alreadyAccount: "Already have an account?",
    cannotRegister: "Could not register user",
    registerReasonEmailExists: "This email is already registered.",
    registerReasonInvalidPayload: "Invalid registration data. Check the fields and try again.",
    registerReasonDbUnavailable: "Registration is temporarily unavailable because the database is not reachable.",
    registerReasonUnknown: "Registration failed on the server. Please try again later.",
    registerAutoLoginFailed: "User was created, but automatic sign-in failed. Please sign in manually.",
    overview: "Overview of jobs and activity",
    jobs: "Jobs",
    type: "Type",
    address: "Address",
    date: "Date",
    status: "Status",
    details: "Details",
    action: "Action",
    loadingJobs: "Loading jobs...",
    noJobs: "No jobs yet.",
    open: "Open",
    takeJob: "Take job",
    assigned: "Assigned",
    cannotTakeJob: "Could not take job",
    takenJob: "Job assigned to you",
    activeJobs: "Active jobs",
    completedJobs: "Completed",
    landlords: "Landlords",
    workers: "Service workers",
    messages: "Messages",
    messageCenter: "Message overview",
    noMessagesYet: "No messages yet.",
    openConversation: "Open conversation",
    conversationWith: "Conversation with",
    unassignedWorker: "Not assigned yet",
    openMap: "Map",
    contact: "Contact",
    contactLandlord: "Contact landlord",
    contactWorker: "Contact service worker",
    reviews: "Reviews",
    averageRating: "Average rating",
    feedbackFromOthers: "Feedback from other users",
    noReviewsYet: "No feedback yet.",
    sendMessage: "Send message",
    writeMessage: "Write message",
    sending: "Sending...",
    send: "Send",
    cannotSendMessage: "Could not send message",
    messageSent: "Message sent",
    roleAdmin: "Admin",
    roleLandlord: "Landlord",
    roleWorker: "Service",
    newMessages: "New notifications",
    markAsRead: "Mark as read",
    switchModeFailed: "Could not switch view. Confirm that the user has both roles.",
    switchModeUpdated: "View updated",
    profileSwitchFailed: "Could not switch mode. Confirm that the user has both roles.",
    profileModeUpdated: "Mode updated",
    profileEditSection: "Edit profile details",
    saveProfile: "Save profile",
    profileUpdated: "Profile updated",
    profileUpdateFailed: "Could not update profile",
    dangerZone: "Danger zone",
    deleteMyAccount: "Delete my account",
    deleteAccountHint: "This deactivates your account and signs you out.",
    confirmDeleteMyAccount: "Are you sure you want to delete your account?",
    deleteAccountSuccess: "Account deleted",
    deleteAccountFailed: "Could not delete account",
    settingsHint: "Use the top-right menu for language, view mode, and account actions.",
    mobileNotifications: "Mobile notifications",
    pushStatusTitle: "Push status",
    pushActiveDevices: "Active devices",
    pushPreference: "Notification setting",
    pushLatestSync: "Latest token sync",
    sendTestPush: "Send test push",
    pushTestSent: "Test push sent",
    pushTestFailed: "Could not send test push",
    pushDisabled: "Mobile notifications are disabled for this user",
    pushNoActiveTokens: "No active mobile devices registered yet",
    noDataYet: "No data yet",
    saveSettings: "Save settings",
    settingsSaved: "Settings saved",
    settingsSaveFailed: "Could not save settings",
    userCreated: "User created",
    userUpdated: "User updated",
    deleteUser: "Delete user",
    confirmDeleteUser: "Are you sure you want to delete user",
    userDeleted: "User deleted",
    deleteUserFailed: "Could not delete user",
    genericError: "Something went wrong. Please try again.",
    unauthorizedError: "You must sign in to continue.",
    forbiddenError: "You do not have access to this action.",
    notFoundError: "The requested item was not found.",
    conflictError: "The action could not be completed due to a data conflict.",
    serviceUnavailableError: "The service is temporarily unavailable. Please try again soon.",
    workerChecklist: "Checklist before completion",
    completionNote: "Message to landlord",
    completeWithNote: "Complete with note",
    completeOrderFailed: "Could not complete order",
    completionDetails: "Execution report",
    noCompletionDetails: "No execution report yet.",
    reviewWorker: "Leave feedback",
    rating: "Rating (1-5)",
    reviewComment: "Feedback text",
    reviewPrompt: "Choose a star rating and write a short review of the service worker.",
    reviewStarLabel: "Stars",
    reviewTextPlaceholder: "Write what worked well and what could be improved",
    reviewSubmitted: "Feedback sent",
    reviewFailed: "Could not send feedback",
    guestCount: "Number of guests",
    guestCountHint: "How many guests the home should be prepared for (cleaning).",
    bedReady: "Beds are prepared",
    bathroomClean: "Bathroom is cleaned",
    kitchenClean: "Kitchen is cleaned",
    floorsVacuumed: "Floors are vacuumed/mopped",
    trashHandled: "Trash is handled",
    keysHandled: "Keys are handled",
    towelsPrepared: "Are towels prepared",
    suppliesRefilled: "Toilet paper, paper towels, and hand soap are refilled",
    allRoomsPhotographed: "Photos have been taken of all rooms",
    userNotFound: "User not found.",
    loading: "Loading...",
    filter: "Filter",
    landlordName: "Landlord name",
    workerName: "Service worker",
    postedDate: "Posted date",
    completedDate: "Completed date",
    serviceType: "Service type",
    serviceState: "Service state",
    all: "All",
    openUnassigned: "Posted, not assigned",
    orderIdNumber: "ID number",
    responsible: "Responsible",
    completedService: "Completed",
    ongoingService: "In progress",
    announcedService: "Posted",
    statusPending: "Pending",
    statusInProgress: "In progress",
    statusCompleted: "Completed",
    prev: "Prev",
    next: "Next",
    sortNewestOldest: "Newest to oldest",
    sortOldestNewest: "Oldest to newest",
    sortNearest: "Nearest",
    searchJobs: "Search jobs...",
    completedOrdersMenu: "Completed jobs",
    completedOrdersHint: "All completed jobs are shown here.",
    createUserTitle: "Create user",
    allUsersTitle: "All users",
    userStatus: "User status",
    userActive: "Active",
    userInactive: "Inactive",
    activate: "Activate",
    deactivate: "Deactivate",
    create: "Create",
    serviceLabel: "Service",
    dateLabel: "Date",
    selectTime: "Select time",
    timeSlotHalfHourOnly: "Choose a time on the hour or half hour",
    addressLabel: "Address",
    commentLabel: "Comment",
    saving: "Saving...",
    createOrderAction: "Create order",
    createOrderSuccess: "Order created",
    selectLandlord: "Select landlord",
    searchLandlord: "Type to search for landlord",
    invalidLandlordSelection: "Select a valid landlord from the list",
    statusUpdated: "Status updated",
    orderAssignedSuccess: "Order assigned",
    imageUploadedSingle: "Image uploaded",
    imageUploadedMultiple: "images uploaded",
    messageDeleted: "Message deleted",
    orderUpdated: "Order updated",
    orderDeleted: "Order deleted",
    orderTitle: "Job",
    landlordLabel: "Landlord",
    assignedLabel: "Assigned",
    noneAssigned: "None",
    manageOrder: "Manage job",
    cancel: "Cancel",
    edit: "Edit",
    addressDateRequired: "Address and date are required",
    invalidServiceType: "Invalid service type",
    guestCountRange: "Guest count must be between 1 and 50",
    confirmDeleteMessage: "Do you want to delete this message?",
    confirmDeleteOrder: "Are you sure you want to delete this order?",
    deleteLabel: "Delete",
    selectWorker: "Select service worker",
    assigning: "Assigning...",
    assignAction: "Assign",
    uploadImage: "Image",
    uploadType: "Type",
    beforeLabel: "Before",
    afterLabel: "After",
    uploadAction: "Upload",
    privateChat: "Private chat",
    privateChatHint: "Only between landlord and service worker",
    chatPendingHint: "Chat is enabled automatically when the job is claimed by a service worker.",
    orderStartRequired: "You must press START before you can write or make changes in this job.",
    orderStartRequiredHint: "Press START to unlock chat, image upload, comments, and the execution report.",
    workerSequenceBlocked: "You must complete earlier jobs before you can start this one.",
    writeComment: "Write comment",
    noImagesYet: "No images uploaded yet.",
    writeMessagePlaceholder: "Write message",
    newMessageNotice: "You have a new message",
    mapPreviewTitle: "Map preview",
    miniMap: "Mini map",
    guestCountPlaceholder: "Guest count (optional)",
    notePlaceholder: "Note",
    saveChanges: "Save changes",
    deleteOrderAction: "Delete order",
    deleteOrderBusy: "Deleting...",
    sendReceipt: "Send receipt",
    sendReceiptBusy: "Sending...",
    receiptLabel: "Receipt",
    checklistMissing: "Missing",
    startAction: "Start",
    receiptAmountPrompt: "Amount in NOK for receipt",
    invalidAmount: "Invalid amount",
    receiptSent: "Receipt sent",
    paymentSectionTitle: "Payment",
    paymentStatusNotStarted: "Not started",
    paymentStatusPending: "Pending payment",
    paymentStatusPaid: "Paid",
    paymentAmountLabel: "Amount",
    paymentPaidAtLabel: "Paid at",
    paymentCreateAction: "Create payment",
    paymentConfirmAction: "Confirm payment",
    paymentResendReceipt: "Resend receipt",
    paymentAmountPrompt: "Amount in NOK for payment",
    paymentCreated: "Payment created",
    paymentConfirmed: "Payment confirmed",
    orderImagesTitle: "Images of your apartment",
    workerImageCountLabel: "Images from service worker",
    showMoreImages: "Show more images",
    privacyLabel: "Privacy",
    termsLabel: "Terms",
    supportLabel: "Support",
    tapOpenJob: "Tap to open job",
    noAccessTitle: "No access",
    adminAccessRequired: "This page requires admin access.",
    fullUserOverviewTitle: "Complete user overview",
    fullUserOverviewSubtitle: "All users in the app with roles, permissions, status, and activity.",
    totalLabel: "Total",
    activePluralLabel: "Active",
    adminsLabel: "Admins",
    landlordsLabel: "Landlords",
    workersLabel: "Service workers",
    permissionsLabel: "Permissions",
    activeModeLabel: "Active mode",
    createdLabel: "Created",
    landlordOrdersLabel: "Orders (landlord)",
    assignedOrdersLabel: "Orders (worker)",
    pushLabel: "Push",
    landlordAndWorkerAccess: "Landlord + Service",
    notFoundUserPanel: "User not found.",
    accountRoleLabel: "Account role",
    activeRoleLabel: "Active role",
    systemHealth: "System health",
    refresh: "Refresh",
    appApi: "App/API",
    database: "Database",
    statusOk: "OK",
    statusError: "Error",
    lastChecked: "Last checked",
    priceCalcTitle: "Choose services and see the final amount",
    priceCalcSubtitle: "This is the total amount the customer must pay before the service is delivered.",
    priceCalcCleaning: "Cleaning",
    priceCalcKeyDelivery: "Key handling",
    priceCalcHomeSize: "Home size (m²)",
    priceCalcLaundryWeight: "Laundry weight (kg)",
    priceCalcBreakfast: "Breakfast trays (per person)",
    priceCalcClothesLaundry: "Clothing laundry (per item)",
    priceCalcTotal: "Final amount to pay",
    priceCalcNotSelected: "Not selected",
    priceCalcAreaSurcharge: "Area surcharge",
    priceCalcPaymentInfo: "The booking is confirmed when this amount is paid.",
    priceCalcDetails: "Price details",
    priceCalcActiveKgPrice: "Active kg price",
    pricePackageTitle: "Package prices",
    pricePackageCleaningTitle: "Deep cleaning",
    pricePackageKeyDeliveryTitle: "Key handling",
    pricePackageLaundryTitle: "Bed linen and towel laundry",
    pricePackageCleaningWeekday: "Package: Weekday (500 NOK)",
    pricePackageCleaningWeekend: "Package: Weekend (600 NOK)",
    pricePackageKeyBefore18: "Package: Weekday before 18:00 (400 NOK)",
    pricePackageKeyAfter18Weekend: "Package: After 18:00 / weekend (500 NOK)",
    pricePackageCleaningWeekdayLabel: "Package cleaning - weekday",
    pricePackageCleaningWeekendLabel: "Package cleaning - weekend",
    pricePackageKeyBefore18Label: "Package key handling - weekday before 18:00",
    pricePackageKeyAfter18WeekendLabel: "Package key handling - after 18:00 and weekends",
    pricePackageLaundryLine: "Pickup, washing, drying, folding, and delivery: 60 NOK per kg",
    priceApartmentLimit: "Applies to apartments up to 75 m².",
    priceAreaAddition: "An additional 100 NOK is added for every started 25 m² above this size.",
    priceSuppliesInfo: "Consumables such as hand soap and toilet paper are covered by the landlord.",
    priceSingleTitle: "Single-service prices",
    priceSingleCleaningTitle: "Cleaning",
    priceSingleKeyDeliveryTitle: "Key handling",
    priceSingleLaundryTitle: "Bed linen and towel laundry",
    priceSingleCleaningWeekday: "Single: Weekday (600 NOK)",
    priceSingleCleaningWeekend: "Single: Weekend (700 NOK)",
    priceSingleKeyWeekday: "Single: Weekday (500 NOK)",
    priceSingleKeyWeekend: "Single: Weekend (700 NOK)",
    priceSingleCleaningWeekdayLabel: "Single cleaning - weekday",
    priceSingleCleaningWeekendLabel: "Single cleaning - weekend",
    priceSingleKeyWeekdayLabel: "Single key handling - weekday",
    priceSingleKeyWeekendLabel: "Single key handling - weekend",
    priceSingleCleaningAddition: "Additional charge: 100 NOK for every started 25 m² above 75 m².",
    priceSingleLaundryLine: "Pickup, washing, drying, and delivery: 65 NOK per kg",
    priceGuestOffersTitle: "Guest offers",
    priceBreakfastTitle: "Breakfast tray",
    priceBreakfastLine: "350 NOK per person",
    priceClothesLaundryTitle: "Clothing laundry",
    priceClothesLaundryLine: "Pickup, washing, drying, folding, and delivery: 45 NOK per item",
    priceClothesLaundryNote: "Does not apply to heavy or bulky garments such as jackets.",
    importantField: "Important field",
    serviceCleaningName: "Move-out cleaning",
    serviceKeyHandlingName: "Key handling",
  },
};

const LanguageContext = createContext<I18n | null>(null);

export function getTranslation(lang: AppLanguage) {
  return (key: string) => messages[lang][key] ?? key;
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<AppLanguage>("no");

  useEffect(() => {
    const stored = window.localStorage.getItem("app_lang");
    if ((stored === "en" || stored === "no") && stored !== lang) {
      const timer = window.setTimeout(() => {
        setLang(stored);
      }, 0);
      return () => window.clearTimeout(timer);
    }
  }, [lang]);

  const value = useMemo<I18n>(() => {
    return {
      lang,
      setLang: (next) => {
        setLang(next);
        window.localStorage.setItem("app_lang", next);
      },
      t: getTranslation(lang),
    };
  }, [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return ctx;
}
